project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Motor Vehicle Collisions"
  author:
    - Tushar Bura (tb3077)
    - Pooja Desur (pgd2120)
  repo-url: https://github.com/poojadesur/Motor-Vehicle-Collisions
  date: November 27, 2023
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: minty
    code-fold: true


